### ISSUE TITLE
[Feature Request] Whitelist

### ISSUE THREAD

**Issue by Madis0** [W-OVERFLOW/Debugify#29]
As a modpack creator, I would like to specifically choose the bugs I fix for my players. 
While the (planned) config to disable individual fixes is great, it soon gets annoying due to the fast rate of updates for the mod itself.

Therefore, I suggest also adding a whitelist option, which enables only the fixes that are enabled within the config file, any new ones will not get enabled by default. One possible way to achieve this could be inversion of the config variables, aka "true" means the fix will not be enabled and "false" means it will be.

**Comment by isXander** [comment]
The config isn't planned. It's already implemented.
But as a modpack, you have to explicitly update the mods right? So when you update, surely you can just change the config then?

**Comment by isXander** [comment]
I can look into having an internal setting not displayed to the users where new unknown bug fixes default to false?

**Comment by Madis0** [comment]
> So when you update, surely you can just change the config then?

Yes, but it means I have to check explicitly which ones were added on every mod version update, that takes a lot of time.

> I can look into having an internal setting not displayed to the users where new unknown bug fixes default to false?

If it's possible this way, yes, that would be great.
