### ISSUE TITLE
[Bug] Game refuses to start with Debugify 1.4.0

### ISSUE THREAD

**Issue by aisukuma** [W-OVERFLOW/Debugify#34]
**Describe the bug**
With just Debugify 1.4.0 (and Fabric API, Cloth API, Cloth Config API, and Mod Menu), the refuses to boot up. Removing Debugify allows the game to boot up normally.

**To Reproduce**
1. Download latest version of Debugify (1.4.0)
2. Start up game

**Expected behavior**
The Minecraft instance is supposed to boot up normally.

**Screenshots**
Vanilla/CurseForge launcher shows this:
![image](https://user-images.githubusercontent.com/22802219/161143874-01f4a283-1fb0-4ff8-8572-742358a00f4c.png)

**Desktop (please complete the following information):**
 - Minecraft Version: `1.18.2`
 - Mod Loader: `Fabric 0.13.3`
 - Mod Version: `1.4.0`

**Additional context**
[Gist think that has the latest.log](https://gist.github.com/aisukuma/4494cd2fdab81af206129e5ee5901ca5)

**Checklist**
- [x] I made sure this bug hasn't already been reported
- [x] I made sure I am using the most up to date mod loader and mod version

**Comment by isXander** [comment]
Confirmed. I will look at this shortly.

**Comment by isXander** [comment]
Posted issue on architectury architectury/architectury-loom#77

this error is due to the workaround I used to get around this

**Comment by isXander** [comment]
Please use 1.4.1. This should fix the issue.

**Comment by aisukuma** [comment]
Awesome, it works now. Thanks for the swift response!
