### ISSUE TITLE
Non-functional discord link in README

### ISSUE THREAD

**Issue by DragonEggBedrockBreaking** [W-OVERFLOW/Debugify#35]
Attempting to use the discord link in README.md results in the below message:
![81309945-5C0D-4275-8EBA-C1D87A0D4372](https://user-images.githubusercontent.com/68545280/161290661-6f76b351-ef36-455c-ac9c-7e587aa05ed3.jpeg)

**Comment by Wyvest** [comment]
fixed, sorry about that
