### ISSUE TITLE
[Patch Request] MC-159163

### ISSUE THREAD

**Issue by Wyvest** [W-OVERFLOW/Debugify#36]
**Checklist**
- [x] I made sure that this bug adheres to the [guidelines](https://github.com/W-OVERFLOW/Debugify/blob/1.18/GUIDELINES.md)
- [x] I am certain this patch has not already been requested
- [x] #37

https://bugs.mojang.com/browse/MC-159163

**Comment by isXander** [comment]
Implementation reference

https://github.com/Toshimichi0915/giz5/blob/master/src/main/java/net/toshimichi/thymine/mixin/ClientPlayNetworkHandlerMixin.java

**Comment by leumasme** [comment]
This is currently played in the Gameplay Fixes category.
https://github.com/isXander/Debugify/blob/5b69f97a80bc4855afdaef239c708cc9364b94db/changelogs/1.21.5/1.21.5%2B1.0.md?plain=1#L4

How do servers detect this?  
Is an alternate fix that only fixes the clienside bounce animation without possibly flagging anticheats possible?  

I find this bug very annoying, so it's rather sad to see the fix being unsafe for multiplayer.
