### ISSUE TITLE
[Patch Request] MC-111442

### ISSUE THREAD

**Issue by Desempregago** [W-OVERFLOW/Debugify#4]
Fireworks don't do damage to Ender Dragon and End Crystals

**Comment by isXander** [comment]
@Wyvest

**Comment by isXander** [comment]
This seems to be intentional but I'm not quite sure. So I will leave this open with a label.

**Comment by MicrocontrollersDev** [comment]
if this bug fix decides to get added, [MC-223774](https://bugs.mojang.com/browse/MC-223774) is a similar issue and might be a good addition as well
