### ISSUE TITLE
[Bug] Mixin transformation of net.minecraft.class_329 failed, causing the game to crash

### ISSUE THREAD

**Issue by NaiNonTH** [W-OVERFLOW/Debugify#40]
**Describe the bug**
After I updated Debugify, I tried to launch the game as normal, but the game crashed along with showing the crash report. (A crash report and the mods I used are further down in this report.)

**To Reproduce**
1. Install Debugify 1.5.0 (may include mods I provided down below in Additional context.)
2. Launch the game as normal
3. Crash...

**Expected behavior**
The game should be launched and playable as normal.

**Desktop (please complete the following information):**
 - Minecraft Version: `1.18.2`
 - Mod Loader: `Fabric 0.13.3`
 - Mod Version: `1.5.0`

**Additional context**
**Crash Report + Mods I Used**
[crash-2022-04-04_19.26.14-client.txt](https://github.com/W-OVERFLOW/Debugify/files/8409657/crash-2022-04-04_19.26.14-client.txt)

**Checklist**
- [x] I made sure this bug hasn't already been reported
- [x] I made sure I am using the most up-to-date mod loader and mod version

**Comment by isXander** [comment]
This is because you have `shadowedactionbar` which is already a feature of Debugify. Specifically [MC-145929](https://bugs.mojang.com/browse/MC-145929). I will mark this mod as incompatible in the next release.

**Comment by isXander** [comment]
resolved in 521edb2

**Comment by NaiNonTH** [comment]
Thank you for checking this report out!
