### ISSUE TITLE
[Suggestion] Describe Patches

### ISSUE THREAD

**Issue by KaspianDev** [W-OVERFLOW/Debugify#42]
This isn't a bug report or patch suggestion. This is a suggestion to the core mod.
Currently, patches are named by their jira id's, however it's hard to know what it does until searching on the internet. With the amount of patches increasing it's hard to remember them all. So my suggestion comes in: add a small description (maybe even link to jira) about the patch you hover on. Thanks.

**Comment by Wyvest** [comment]
Not that familiar with whatever config library Xander uses in Debugify, but I don't think we can add tooltips / descriptions to the settings.

Also, https://github.com/W-OVERFLOW/Debugify/blob/1.18/PATCHED.md exists

**Comment by isXander** [comment]
There is a technical limitation to doing this. It gets the bug name from the package of the mixin. The only way I could think of doing this is to use an API call?

**Comment by KaspianDev** [comment]
It should be possible to add hyperlinks tho. You can just redirect to https://bugs.mojang.com/browse/MC-whatever
