### ISSUE TITLE
[Patch Request] MC-144761

### ISSUE THREAD

**Issue by oliviathevampire** [W-OVERFLOW/Debugify#43]
**Checklist**
- [x] I made sure that this bug adheres to the [guidelines](https://github.com/W-OVERFLOW/Debugify/blob/1.18/GUIDELINES.md)
- [x] I am certain this patch has not already been requested
- [x] I know that this patch isn't already in the latest version of the mod

**Comment by isXander** [comment]
[code analysis](https://bugs.mojang.com/browse/MC-144761?focusedCommentId=780425#comment-780425)

**Comment by isXander** [comment]
Cannot fix due to [incompatibility with Sodium](https://github.com/CaffeineMC/sodium-fabric/blob/1.18.x/dev/src/main/java/me/jellysquid/mods/sodium/mixin/features/texture_updates/MixinSpriteInterpolated.java#L36) maybe suggest fixing this on the sodium repo
