### ISSUE TITLE
Debugify 1.1.0 + Sodium Extra incompatibility

### ISSUE THREAD

**Issue by LeeroyGarfield** [W-OVERFLOW/Debugify#5]
### Bug description

Debugify 1.1.0 doesn't work with [Sodium Extra](https://www.curseforge.com/minecraft/mc-mods/sodium-extra) by FlashyReese, but its previous version, 1.0, does.

### Steps to reproduce

1. Enable the following: [Fabric API 0.48.0](https://www.curseforge.com/minecraft/mc-mods/fabric-api/files/3689020), Debugify 1.1.0, [Sodium 0.4.1+build.15](https://www.curseforge.com/minecraft/mc-mods/sodium/files/3669187), and [Sodium Extra 0.4.2](https://www.curseforge.com/minecraft/mc-mods/sodium-extra/files/3682548)
2. Launch the game
3. Wait until the loading bar reaches the end

### Expected behavior

When the loading bar reaches the end, it will become stuck in a loop.

https://user-images.githubusercontent.com/87123836/159152062-c5ab5c53-95f0-43d4-9129-27a55f92d691.mp4

### Anything else?

I like bug fixes, so I automatically like your Debugify!

**Comment by Wyvest** [comment]
Hi! Could you go to discord.gg/woverflow so we can further troubleshoot the issue? Thanks!

**Comment by isXander** [comment]
Your logs will probably be spamming something about the resource manager. Can you send the full logs? There may be a conflicting bug fix between Sodium Extra and the new patch in Debugify.

**Comment by isXander** [comment]
Fixed in 1.2.0 out now on modrinth
