### ISSUE TITLE
[Patch Request] MC-2112

### ISSUE THREAD

**Issue by PoggyMan** [W-OVERFLOW/Debugify#54]
**Checklist**
- [x] I made sure that this bug adheres to the [guidelines](https://github.com/W-OVERFLOW/Debugify/blob/1.18/GUIDELINES.md)
- [x] I am certain this patch has not already been requested
- [x] I know that this patch isn't already in the latest version of the mod

Link to bug on the bug tracker thingy https://bugs.mojang.com/browse/MC-2112

**Comment by isXander** [comment]
This behaviour is now standard in Minecraft. It would be very bad to change this. Especially when using it on servers.
