### ISSUE TITLE
[Bug] Debugify breaks JEI's search bar

### ISSUE THREAD

**Issue by Peach774** [W-OVERFLOW/Debugify#55]
**Describe the bug**
With debugify, the JEI search bar can not be clicked out of or escaped from.

**To Reproduce**
1. Install Debugify and JEI
2. Create a new world
3. Type something into JEI
4. Try to press escape or click outside the search bar to stop typing.
5. Be forced to click an item with a recipe to stop typing in the search bar.

**Expected behavior**
You should be able to click outside of the JEI search bar, or press Esc to stop typing.

**Desktop (please complete the following information):**
 - Minecraft Version: `1.18.2`
 - Mod Loader: `Forge 40.0.44`
 - Mod Version: `1.7.0`

**Additional context**
Any version of JEI for 1.18.2 should work

**Checklist**
- [x] I made sure this bug hasn't already been reported

- [x] I made sure I am using the most up to date mod loader and mod version

**Comment by isXander** [comment]
I suggest you disable that fix in the meantime while I get that fixed.

**Comment by Peach774** [comment]
Following up - disabling the fix for MC-147605 fixes this, so something with the implementation of the fix for MC-147605 is broken

**Comment by isXander** [comment]
Fixed in 2ebeca5

**Comment by mezz** [comment]
Thanks for the fix! What was the issue with JEI?

**Comment by isXander** [comment]
> Thanks for the fix! What was the issue with JEI?

Wasn't anything with JEI. This bug fix broke when there were widgets and text fields in the same gui. The text field would never focus because the widget was already focused.
