### ISSUE TITLE
[Bug] Crash when starting up forge server.

### ISSUE THREAD

**Issue by Gbergz** [W-OVERFLOW/Debugify#56]
**Describe the bug**
When the mod is loaded on servers, it crashes.

**To Reproduce**
1. Install a 1.18.2 Forge server.
2. Add Debugify
3. Start Server
4. Wait.
5. Crash.

**Expected behavior**
That the server starts without issues.

**Crash-Report**
https://gist.github.com/Gbergz/2c080a1284772702d259c7bedd798b16

**Desktop (please complete the following information):**
 - Minecraft Version: `1.18.2`
 - Mod Loader: `Forge 39.0.45`
 - Mod Version: `1.7.1`

**Checklist**
- [X] I made sure this bug hasn't already been reported.
- [X] I made sure I am using the most up to date mod loader and mod version.

**Comment by isXander** [comment]
Sorry about this. Never got to test forge server as I had some issues launching it in development.

Can repeat. Looking into this now.
