### ISSUE TITLE
[Bug] MC-53312 Fix isn't perfect

### ISSUE THREAD

**Issue by Julienraptor01** [W-OVERFLOW/Debugify#58]
**Describe the bug**
[MC-53312](https://bugs.mojang.com/browse/MC-53312) affect the evoker, the illusionner, the villager, the witch and the zombie-villager. Techniacally the pillager, the vindicator and the wandering trader uses similar models but the bug doesn't affect them with the vanilla textures. Currently only the villager, the wandering trader and the witch are affected by this Fix.

**To Reproduce**
Look at all the entities i named above

**Expected behavior**
Well the fix should be applied to all the entities i named above

**Screenshots**
How it is
![2022-04-14_17 57 54](https://user-images.githubusercontent.com/49841713/163428693-f5f3aee0-f60e-4d6a-99a1-e1dbf074feec.png)

How it should be
![2022-04-14_17 58 16](https://user-images.githubusercontent.com/49841713/163428722-0fd764bc-8b83-4543-96d9-103a8d774e46.png)

How it is with some debugging pack
![2022-04-14_17 57 36](https://user-images.githubusercontent.com/49841713/163428780-e96e7511-e910-4ac6-aa2a-4c802497a2e8.png)

How it should be with debugging pack
![2022-04-14_17 57 13](https://user-images.githubusercontent.com/49841713/163428843-d71b5925-6459-4d9a-84c6-0bc994619590.png)

**Desktop (please complete the following information):**
 - Minecraft Version: `1.18.2`
 - Mod Loader: `Fabric 0.13.3`
 - Mod Version: `1.7.1`

**Additional context**
The first pack uses CEM mod to show the fixed models and the second is my debug pack
[(V)Illager Cloak Fix.zip](https://github.com/W-OVERFLOW/Debugify/files/8490667/V.Illager.Cloak.Fix.zip)
[TEST (V)Illager Cloak Fix.zip](https://github.com/W-OVERFLOW/Debugify/files/8490668/TEST.V.Illager.Cloak.Fix.zip)

**Checklist**
- [x] I made sure this bug hasn't already been reported
- [x] I made sure I am using the most up to date mod loader and mod version

**Comment by isXander** [comment]
Thanks a lot for this report.

I have identified the issue and have fixed the issue. Release soom!
