### ISSUE TITLE
[Bug] Crash on config GUI interaction

### ISSUE THREAD

**Issue by Madis0** [W-OVERFLOW/Debugify#59]
**Describe the bug**
Game presumably crashes when interacting in Debugify. Presumably because I am also using Not Enough Crashes to overwrite that.

**To Reproduce**
1. Go to Mod Menu
2. Click on Debugify's config button
3. Click or scroll anywhere in the config

**Expected behavior**
No crash, just toggling bugfixes etc

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - Minecraft Version: `1.18.2`
 - Mod Loader: `Fabric 0.13.3`
 - Mod Version: `1.7.1`

**Additional context**
Fabulously Optimized 3.5.0 (released soon)
https://bytebin.lucko.me/0Dbrwzyj3B

**Checklist**
- [x] I made sure this bug hasn't already been reported
- [x] I made sure I am using the most up to date mod loader and mod version

**Comment by isXander** [comment]
https://hst.sh/qixihomage

crashlog without NEC
