### ISSUE TITLE
[Bug Report] Cannot rename items with the anvil

### ISSUE THREAD

**Issue by Abbanon** [W-OVERFLOW/Debugify#62]
The anvil GUI prevents me from clicking on, or typing in, the item name field with this mod active.

 - Minecraft Version: `1.18.2`
 - Mod Loader: `Fabric 0.13.3`
 - Debugify Version: `1.7.2` (bug also present in `1.7.1`, possibly even earlier versions)
 
 Minecraft log with modlist (in case it's relevant)
 https://paste.ee/p/9HqMW

**Comment by isXander** [comment]
Does disabling MC-147605 fix the issue?

**Comment by Abbanon** [comment]
It absolutely does fix the issue!

**Comment by isXander** [comment]
Okay. Will look into this.
