### ISSUE TITLE
[Bug] Crash on launch

### ISSUE THREAD

**Issue by Mattabase** [W-OVERFLOW/Debugify#67]
**Describe the bug**
game crashes when launched 

**To Reproduce**
install mod

**Expected behavior**
not crash

**Desktop (please complete the following information):**
 - Minecraft Version: `1.18.2`
 - Mod Loader: `Fabric 0.13.3`
 - Mod Version: `1.8.0`

**Checklist**
- [x] I made sure this bug hasn't already been reported
- [x] I made sure I am using the most up to date mod loader and mod version

https://gist.github.com/4a37e0c2217cc7aabd7fb17f86060947

**Comment by isXander** [comment]
Duplicate of #66
