### ISSUE TITLE
[Bug Report] Log displays Realms trial-related errors on the main menu

### ISSUE THREAD

**Issue by Abbanon** [W-OVERFLOW/Debugify#70]
Log: https://paste.ee/p/dFZO1

Information shows this is likely the result of either `MC-234898` or `MC-249021` set to `true` - possibly both?

 - Minecraft Version: `1.18.2`
 - Mod Loader: `Fabric 0.13.3`
 - Debugify Version: `1.8.1`

**Comment by isXander** [comment]
This usually happens anyway, and is the cause of the bugs.
