### ISSUE TITLE
[Bug] Ironically, Debugify Crashes On Startup

### ISSUE THREAD

**Issue by HacoKavanah** [W-OVERFLOW/Debugify#71]
[2022-04-19-6.log](https://github.com/W-OVERFLOW/Debugify/files/8510152/2022-04-19-6.log)

The issue is fixed when removing debugify.

 - Minecraft Version: `1.18.2`
 - Mod Loader: `Fabric 0.13.3`
 - Mod Version: `debugify-1.8.1-fabric-1.18.2.jar`

**Comment by thelegitdolt** [comment]
i am sorry :((((
