### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by thelegitdolt** [W-OVERFLOW/Debugify#73]
crash

https://gist.github.com/thelegitdolt/83f3c11e8ebc9cdd2b3fd044648bff93

I have installed 1.9.0 and it still crashes, doubt this is a duplicate of #71 as said

**Comment by isXander** [comment]
Seems unrelated to Debugify. Nonetheless, I will look into it.

**Comment by thelegitdolt** [comment]
thank you! it does go away when i take out debuggify. i'll do a binary search on my modpack to see what's causing the issue

**Comment by isXander** [comment]
That would help a lot, thanks.

**Comment by thelegitdolt** [comment]
this is apparently because i didn't have cloth config involved. sorry! i removed a bunch of mods and it finally showed me the dependencies page.
