### ISSUE TITLE
[Bug] Fix for MC-122477 causing only backspace to work in textfields on linux

### ISSUE THREAD

**Issue by JosefLitos** [W-OVERFLOW/Debugify#77]
When the fix for occasional appearance of 't' when opening chat is turned on, no textfields receive text input. Only button working is backspace.
Tried with:
- [Blur](https://www.curseforge.com/minecraft/mc-mods/blur-fabric)
- [MiniHUD](https://www.curseforge.com/minecraft/mc-mods/minihud)

Loader: Fabric, latest, 1.18.2
Debugify: 1.9.0

**Comment by isXander** [comment]
*use the template*

**Comment by isXander** [comment]
please edit your original post to include
- loader e.g. fabric
- debugify version

**Comment by isXander** [comment]
I cannot repeat on linux-zen 5.17 arch linux. What kernel type + version and distro are you on?

**Comment by JosefLitos** [comment]
latest mainline, on arch

**Comment by JosefLitos** [comment]
if you add a shape in minihud and try to edit its radius by opening the edit screen while in a world, you won't be able to write anything to the config - the radius will be changeable only using the buttons.

**Comment by isXander** [comment]
I can't really fix a bug I can't repeat. Small chance but maybe linux-zen fixes this?

**Comment by JosefLitos** [comment]
I use a fix for the same bug from TieFix (or qol-fixes, not sure which one) and it causes no side effects at all. I shall try linux-zen.

**Comment by JosefLitos** [comment]
I have no clue, how you fixed it, but you did.
Thank you.

**Comment by isXander** [comment]
Counted amount of polls, not client ticks.
