### ISSUE TITLE
[Patch Request] MC-26757

### ISSUE THREAD

**Issue by Poopooracoocoo** [W-OVERFLOW/Debugify#78]
**Checklist**
- [x] I made sure that this bug adheres to the [guidelines](https://github.com/W-OVERFLOW/Debugify/blob/1.18/GUIDELINES.md)
- [x] I am certain this patch has not already been requested
- [x] I know that this patch isn't already in the latest version of the mod

https://bugs.mojang.com/browse/MC-26757
Large item tooltips can get cut off at the edges of the screen

v1.6.0 added a fix for this, but 1.7.0 removed it. 

[ToolTipFix](https://www.curseforge.com/minecraft/mc-mods/tooltipfix) fixes this issue but doesn't do so in various mod config screens such as Debugify's config screen. Probably a separate issue worth filing?
<img width="960" alt="image" src="https://user-images.githubusercontent.com/51363864/164896483-8cf32a79-4000-4995-b721-bc067203e5f3.png">
Cursor drawn on with Paint :P

**Comment by isXander** [comment]
I will seriously look into implementing this mod into Debugify. Hasn't been updated since October of last year and the mixins look really inefficient and nasty.

**Comment by isXander** [comment]
re-added this patch into Debugify as of 1.10.0 (unreleased). Again, it uses the same method as bedrock as it is simpler and it's parity.
